openapi: '3.0.0'
info:
  version: '1.0'
  title: ClinGen API
  description: >-
    Rest API for ClinGen Allele Registry
  termsOfService: https://www.clinicalgenome.org/
  contact:
    name: Piotr Pawliczek
    x-role: responsible developer
    email: Piotr.Pawliczek@bcm.edu
    x-id:
      - 'https://github.com/ppawliczek'
servers:
  - url: 'http://reg.test.genome.network'
    description: 'Production server'
tags:
  - name: variant
  - name: annotation
  - name: query
  - name: translator
paths:
  '/alleles':
    get:
      summary: 'Returns variant information'
      parameters:
        - name: alleles
          in: query
          description: >-
            e.g. ClinVar.RCV=RCV0000168487
          required: true
          schema:
            type: string
          x-valueType:
            - 'http://identifiers.org/clinvar/'
            - 'http://identifiers.org/hgvs/'
          x-requestTemplate:
            - valueType: 'http://identifiers.org/clinvar/'
              template: ClinVar.RCV={{input}}
            - valueType: 'http://identifiers.org/hgvs/'
              template: MyVariantInfo_hg19.id={{input}}
      responses:
        '200':
          description: 'Variant Object'
          x-responseValueType:
            - path: edge.obj
              valueType: 'http://identifiers.org/ncbigene/'
          x-JSONLDContext:
            'https://raw.githubusercontent.com/NCATS-Tangerine/translator-api-registry/master/biolink/jsonld_context/biolinks_gene_context.json'